sprint-5/step-1
Musmaxim/React-burger pull request #6
Opened 2023-06-12 13:03 UTC by Musmaxim

2023-06-12 17:15 UTC, kyzinatra commented on src/copmonents/App/App.tsx
> +import Logout from "../../pages/Profile/Logout";
Надо исправить: заказы в работе не отображаются  (скрин)

2023-06-12 17:18 UTC, kyzinatra commented on src/pages/Profile/OrderHistory.tsx
> +    dispatch(connect(`${BURGER_WSS}orders?token=${accessToken}`));
Надо исправить: Заказы необходимо сортировать в порядке от новых к старым. Сейчас наоборот

2023-06-12 17:20 UTC, kyzinatra commented on src/pages/Profile/OrderHistory.tsx
> +      if (status !== WebsocketStatus.OFFLINE) dispatch(disconnect());
Надо исправить: из-за strict mode в react происходит  дублирование открытых сокетов  (скрин)

2023-06-12 17:21 UTC, kyzinatra commented on src/services/middlewares/SocketMiddleware.ts
> +              dispatch(wsConnect(url));
Отлично! Очень круто, что вы сделали reconnect

2023-06-12 17:21 UTC, kyzinatra commented on src/services/middlewares/SocketMiddleware.ts
> +          socket.close();
Отлично! Круто, что вы закрываете соединение

2023-06-12 17:25 UTC, kyzinatra commented
Выглядит очень круто! Видно, что проделана большая работа. Но все же есть моменты на которые стоит обратить внимание.
Подробнее: 

**Что важно исправить:**

-  заказы в работе не отображаются (скрин)

-  Заказы необходимо сортировать в порядке от новых к старым. Сейчас наоборот
-  из-за strict mode в react происходит дублирование открытых сокетов (скрин)


**Что понравилось:**

-  Очень круто, что вы сделали reconnect
-  Круто, что вы закрываете соединение


**Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.**

2023-06-13 20:15 UTC, kyzinatra requested changes
Вы отлично потрудились над исправлением замечаний, но сокеты все еще остаются открытыми даже после выхода со страницы. Посмотрите в devtools->network, чтобы при перезаходе на страницу `feed` не оставалось старых сокетов открытыми.
![image](https://github.com/Musmaxim/React-burger/assets/51288221/c28655f7-9b3e-463a-96eb-f8f8e26357c3)

2023-06-13 20:15 UTC, kyzinatra commented on src/copmonents/App/App.tsx
Можно лучше: в данном случае `useMemo` лишне. Взять `location.state && location.state.background` быстрее чем вызывать `useMemo`

2023-06-15 19:17 UTC, Musmaxim commented
Извините, но я честно не знаю, как еще сделать) теперь сокет all и profile открываются только один раз, но он вроде все равно дублируется один раз.

2023-06-15 20:03 UTC, kyzinatra commented
Давайте попробуем разобраться вместе, @Musmaxim. Начнем с того, что разберемся что происходит и чего мы добиваемся:

Из-за strict mode в реакте все компоненты рендерятся 2 раза. Это нужно в dev режиме, чтобы выявлять баги связанные с наличием грязных компонентов. 

Изначально в react все компоненты (функции) должны быть чистыми. То есть они не должны менять никаких внешних переменных или структур (проще говоря при любом вызове с одинаковыми входными `props` должна возвращаться одинаковая разметка). 

Это важное условие, но в реальном мире это невозможно. Компоненты должны получать данные от сервера, ставить обработчики итд, что уже делает их грязными. Чтобы это контролировать есть хук `useEffect`. В нем можно делать так называемые внешние эффекты (как раз ту грязную логику), но react просит нас всегда очищать все грязные действия после выполнения `useEffect()`, к примеру вы удаляем `eventListener` в компоненте `Modal`. И как раз для того, чтобы контролировать это поведение нужен `strictMode`. По сути, наш сокет должен работать примерно также как и `addEventListener`. Если мы его включили он включен. Любое повторное включение должно игнорироваться. Если мы его выключили он закрылся и мы можем его открыть снова. Давайте на примере.

В компоненте `Feed.tsx` я уберу все условия на offline и оставлю только connect и disconnect

```js
useEffect(() => {
  dispatch(connect(`${BURGER_WSS}orders/all`));
  return () => {
	dispatch(disconnect(`${BURGER_WSS}orders/all`));
  };
}, []);
```

В сокете я на событие подключение я проверю нет ли у меня уже активного сокета. Если есть, то игнорирую событие:

```js

if (wsConnect.match(action)) {
 if (!socket)
      url = action.payload;
      socket = new WebSocket(url);
      isConnected = true;
      dispatch(wsConnecting());
    }
}
      
```

Вот собственно и все. Теперь посмотрим на то, что происходит с сокетами

Вот пример как я 3 раза перезашел на страницу `feed`
![image](https://github.com/Musmaxim/React-burger/assets/51288221/e92431c2-a418-41be-9815-743d32bd173e)

Заметим, что у нас есть 3 сокета `Finished` - это как раз проверка из `strictMode`
Те же сокеты, которые открылись и поработали закрылись после выхода. У нас больше нет ситуации когда одновременно открыто 2 сокета сразу. 

Вот я снова зашел на `feed` и вижу 1 единственный открытый  сокет.
![image](https://github.com/Musmaxim/React-burger/assets/51288221/77f39cf2-29ff-41b7-ae09-277534aabd75)


Именно поэтому вы правильно сделали что разделили 2 сокета и стали их не делать в 1 middleware, хотя казалось бы, так проще. Мы  таким образом обеспечиваем то, что каждый конкретный сокет открыт  в 1 экземпляре
```js
 getDefaultMiddleware().concat(
      socketMiddleware(wsFeedActions),
      socketMiddleware(wsProfileActions)
    ),
```
  
  Надеюсь стало более понятно что происходит, и зачем мы все это делаем ^-^

2023-06-17 09:31 UTC, Musmaxim commented
Спасибо, все оказалось как всегда просто, когда перед глазами простое объяснение)

2023-06-21 18:11 UTC, merged